name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Deploy Subgraphs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Set npm cache directory
        run: npm config set cache .npm-cache --global
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # pin@v2
        with:
          path: |
            .npm-cache
            node_modules
          key: ${{ runner.os }}-alpine-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-alpine-node-
        continue-on-error: true
      # issue with github actions, see https://github.com/actions/setup-node/issues/214#issuecomment-810829250
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - run: npm ci
      - name: Authenticate
        run: npm run auth ${{ secrets.ACCESS_TOKEN }}
      - name: Deploy optimistic kovan main subgraph
        run: node scripts/deploy.js -t kwenta -s main -n optimism-kovan
        env:
          NETWORK: optimism-kovan
      - name: Deploy optimistic mainnet main subgraph
        run: node scripts/deploy.js -t kwenta -s main -n optimism
        env:
          NETWORK: optimism
      - name: Deploy optimistic kovan rates subgraph
        run: node scripts/deploy.js -t kwenta -s latest-rates -n optimism-kovan
        env:
          NETWORK: optimism-kovan
      - name: Deploy optimistic mainnet rates subgraph
        run: node scripts/deploy.js -t kwenta -s latest-rates -n optimism
        env:
          NETWORK: optimism
